"""initial schema

Revision ID: 755ee710511d
Revises: 
Create Date: 2026-06-26 12:40:33.769366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '755ee710511d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_action_logs_workspace_id', 'action_logs', ['workspace_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('autonomy_level', sa.Enum('supervised', 'assisted', 'autonomous', name='autonomylevel', native_enum=False), server_default=sa.text("'supervised'"), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brand_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('audience', sa.Text(), nullable=False),
    sa.Column('tone', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('avoid', sa.JSON(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_profiles_workspace_id'), 'brand_profiles', ['workspace_id'], unique=False)
    op.create_table('content_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('generating', 'ready', 'failed', name='planstatus', native_enum=False), server_default=sa.text("'generating'"), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_plans_workspace_id'), 'content_plans', ['workspace_id'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('angle', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('hashtags', sa.JSON(), nullable=False),
    sa.Column('suggested_time', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending_approval', 'approved', 'scheduled', 'published', 'rejected', name='poststatus', native_enum=False), server_default=sa.text("'pending_approval'"), nullable=False),
    sa.Column('postiz_post_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['content_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_workspace_id'), 'posts', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_workspace_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_content_plans_workspace_id'), table_name='content_plans')
    op.drop_table('content_plans')
    op.drop_index(op.f('ix_brand_profiles_workspace_id'), table_name='brand_profiles')
    op.drop_table('brand_profiles')
    op.drop_table('workspaces')
    op.drop_index('ix_action_logs_workspace_id', table_name='action_logs')
    op.drop_table('action_logs')
    # ### end Alembic commands ###
